#!/bin/bash

test -d target || \
    mkdir target

rm -f target/*

for PROJECT in ./*/platformio.ini; do
    for EXTENSION in "elf" "hex"; do
        for BINARY in ${PROJECT%/platformio.ini}/.pio/build/*/firmware.${EXTENSION}; do
            PROJECT_NAME=${PROJECT%/*}
            PROJECT_NAME=${PROJECT_NAME##*/}
            ENVIROMENT_NAME=${BINARY%/*}
            ENVIROMENT_NAME=${ENVIROMENT_NAME##*/}
            
            cp ${BINARY} "target/${PROJECT_NAME}-${ENVIROMENT_NAME}.${EXTENSION}"
        done
    done
done