name: Clean artifacts

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  delete-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: kolpav/purge-artifacts-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          expire-in: 7days
